### ISSUE TITLE
Walk animations for bows miss first (idle) and last frame

### ISSUE THREAD

**Issue by sanderfrenken** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#104]
https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Normal_light

**Comment by jrconway3** [comment]
I can't find the oversize body, but I think now its just repositioning the body from the existing walk animations? That's an interesting way to handle it. Also makes it a bit complicated as I have to figure out how to properly line it up in a larger frame to create a template so I can fix this.

Seems like all the bows have the same problem. Also, it appears the first frame (idle) is the only frame not in oversize, as oversize contains all frames after idle. Its possible we'll need the first frame in oversize as well, but I'll play around with it. Maybe I can squeeze the bow into the regular idle frame and still make it look good in the animation.


Just trying to create templates in Aseprite right now so I can make some of these modifications.

**Comment by jrconway3** [comment]
I've got a good Aseprite template for this now and mapped all the pieces to the individual missing spots, but there's still the issue of frame 1 not being in the "oversize". I'll try to see if I can add the bows to the base idle frame instead, but we might have problems if there's not enough room to do so. I still have to test this on my local copy to see how it looks anyway.

**Comment by sanderfrenken** [comment]
Hee! I asked bluecarrot as well to look into this issue, he has all the sprites already AFAIK. So maybe better to wait for him.. Sorry I hope you didn't spent too much time yet!!!

**Comment by jrconway3** [comment]
No problem, not a big deaL I now have a template set aside so I can do other fixes later.
