### ISSUE TITLE
Can we have credits support the path if there's no direct image path?

### ISSUE THREAD

**Issue by jrconway3** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#108]
The credits file right now is a bit cumbersome to support all palettes. I can understand that maybe some palettes were added by other people and need extra credentials, but I think we can clean this up a bit in this kind of way:

Maybe we can check by the exact path first, otherwise, we see if any path is within the range? For example:

`hair/extensions/braidl/,,David Conway Jr. (JaidynReiman),"OGA-BY 3.0+, CC-BY 3.0+, CC-BY-SA 3.0, GPL 3.0",https://opengameart.org/content/lpc-1-hairstyle-2-hair-extensions-3-previously-unofficially-released-hairstyles,,,,,,,,,,,,,,,OK`

If my braid is in the path, then this will be the fallback if the individual images don't exist. That will make it much easier to bulk add recolors or alternate formats.

Let's say, for example, I make some fixes to missing frames like in these bow sprites::
`weapon/ranged/bow/great,"modified by daneeklu, from ""normal"" bow by wulax; walk animations by pvigier; split into layers and tweaked for v3 character bases by bluecarrot16","Daniel Eddeland (daneeklu), gr3yh47, Johannes Sjölund (wulax), Pierre Vigier (pvigier)",CC-BY-SA 3.0,https://opengameart.org/content/lpc-weapons-two-bows-a-spear-and-a-trident,https://opengameart.org/content/lpc-walk-animations-for-bows,,,,,,,,,,,,,,`

After I make these modifications, I add my name:
`weapon/ranged/bow/great/walk,,"David Conway Jr. (JaidynReiman), Daniel Eddeland (daneeklu), gr3yh47, Johannes Sjölund (wulax), Pierre Vigier (pvigier)",CC-BY-SA 3.0,https://opengameart.org/content/lpc-weapons-two-bows-a-spear-and-a-trident,https://opengameart.org/content/lpc-walk-animations-for-bows,,,,,,,,,,,,,,`

On all walk animations it will include my name in the list and any sub-directories, but if that path is missing, it falls back to the higher up one.

Is that something which is reasonable to do? I think this could work and make it much easier to update these credits.

**Comment by jrconway3** [comment]
I think I'll just write up a method to handle this myself and share it. I don't think it'll be too hard to implement, just need to take a closer look at the code being used.

**Comment by jrconway3** [comment]
I have a hypothetical in the WIP listed above:
https://github.com/jrconway3/Universal-LPC-Spritesheet-Character-Generator/pull/2

Going to play around with this and see how well it works.

**Comment by jrconway3** [comment]
Updated that branch again, I think I fixed the remaining bugs in it. It seems to be working pretty well now...

**Comment by sanderfrenken** [comment]
Fixed with https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/109
