### ISSUE TITLE
Long Hairstyle Replaced by Longknot

### ISSUE THREAD

**Issue by jrconway3** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#111]
Just figured I should make an official issue for this (just in case someone else notices), but I already have a hotfix PR open:
https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/110

In the last update that got merged, I cleaned up my old hairstyles a tad bit, but apparently I accidentally pasted the longknot updates into long instead...

![issue-long-replaced-with-longknot](https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/assets/3292008/715fc64a-dfb8-4ebc-8a4b-b03fa0b0e587)

**Comment by sanderfrenken** [comment]
Fixed by https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/110
