### ISSUE TITLE
"Muscular" Body Type Missing "Shoot" Base Animation and All "Expanded" Animations *LOW PRIORITY*

### ISSUE THREAD

**Issue by jrconway3** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#130]
The "Muscular" body type has the exact same bases as the "Male" body type. As such, all we have to do is copy/paste the "Male" Shoot animations and add in the "Muscular" shading. I haven't done much work with altering base models yet, so IDK if I'll be the one to do this or not.

Either way, though, I'm creating this card because it is something that's missing so we can track what's still missing and needs to be added.

UPDATE:
I have decided to close Issue #138 and have this one just be for fixing all "Muscular" animations, rather than splitting it into "legacy" and "expanded".

Expanded includes:
Climb, Emotes, Run, and Revised Combat

**Comment by jrconway3** [comment]
Turns out I was wrong, Muscular _does_ have a slightly bigger frame. Its only one pixel, though, so its not a huge difference. The shading is probably the hardest part about this anyway.

**Comment by The-End-Is-Near** [comment]
@jrconway3 
Also noticed more missing animations for muscular: Emote, Climb, Combat Handle, and 1-handed attacks. I'm unsure if this is intentional, but just wanted to point it out

**Comment by jrconway3** [comment]
https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/issues/138

I referenced that in Issue #138 because I'm trying to keep distinct the "old" animations and the "new" sets. The "new" sets are Climb, Idle, Jump, Sit, Emotes, Run, and Eliza's new Combat animations. Prior to me adding those into this sheet, only everything "above" climb existed.

IMO, doing stuff above "climb" is more important because that's the legacy structure, so I was keeping those things distinct from the newly added animations.


...not that I intend on doing Muscular any time soon, mind you. At this point in time, my focus is on filling out as many Male/Female/Teen assets as I can, and secondary to that is Pregnant (because that's significantly easier than Muscular). Muscular requires even more effort to make because it increases the body size yet again, and its not even OGA-BY which hurts my desire to prioritize it even more.

These cards are mostly if other people are interested in working on them, or if there's enough interest from other people, it might convince me to do them myself. But so far I'm not invested in doing them at this time.


And for some animations, I'm honestly not sure how to do it. The hand cutouts on the head really mess up some of the animations, making it difficult to add distinctions there. That's probably why Muscular is not already complete on the shoot animation--because they'd have to increase the arm size on the head cutouts, which means unique head cutouts just for one body type. To solve this problem for the normal Male body vs Female body (Male body is much thicker), they simply used the same body size for most of the "shoot" animations to solve the cutout problem.

**Comment by jrconway3** [comment]
Okay, so I opted to just close the other card and merge that over here. The other card is "closed" because the Male assets are long-done, and this will just be the card for Muscular. That cleans up the list of issues a tiny bit.

**Comment by jrconway3** [comment]
I'm moving this card here:
https://github.com/jrconway3/Universal-LPC-Spritesheet-Character-Generator/issues/5

I want to clear out this list and don't want people viewing this to feel obligated to have to work on it, so I'm putting these issues into my fork instead.
