### ISSUE TITLE
Map All Inhuman Heads to All Frames

### ISSUE THREAD

**Issue by jrconway3** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#149]
With the recent expansion to add new animation frames, I already mapped all HUMAN heads to all frames. What's currently missing, however, are all the non-human heads, so that is something that should get taken care of soon.

Additionally, child heads are not mapped over the missing animations I just added. This is hardly a big concern, as the current trend with child heads is just laying them over the blank frames by the default idle position. However, it would be nice to throw that in for consistency, but otherwise its super minor.

**Comment by jrconway3** [comment]
Now with the cutouts in place I can make this a priority soon-ish. The head cutouts will be needed for all of these.

**Comment by jrconway3** [comment]
This is definitely going to be the next update. Because I have to redo the directories anyway with the drop of the `universal/ sit/ jump/ run/` idle/ structure, I'm just going to shift it to having the race of the head be the main directory and adult/child the sub-directory. I may try to add recolors to some assets (like skeleton and zombie) which don't have them yet. I don't think pumpkin will be too easy to do because pumpkin appears to have WAY more colors than we have recolor palettes for, so that probably won't work. It'd be cool to have blue/green pumpkins for example, but I don't see an easy way to do it.

Zombie/Skeleton I think I might be able to do, though.

**Comment by jrconway3** [comment]
@fnaith Feel free to try looking through this update and let me know if anything is missing! All heads at this point should be mapped to all frames, but if anything looks off please let me know.

**Comment by fnaith** [comment]
Cool, I am making yeyanither animation generator.
So if something is looks off, I may find it eventually.

**Comment by jrconway3** [comment]
I checked all heads, everything looks good right now. The slash animations look kinda off in some situations, so maybe there's something wrong with my positioning there, but MOST heads look ever so slightly off and it may just be because of the specific animation itself shifting the head position so much, so maybe that's fine and I'm just seeing this.

So I'm closing this issue now.
