### ISSUE TITLE
Are there some issues with Firefox?

### ISSUE THREAD

**Issue by manucontrovento** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#15]
Hi everyone!
since some days I can't access the character generator anymore:

![immagine](https://user-images.githubusercontent.com/56541575/138062983-41a34ffc-8f25-421e-989d-a82f9fc8c4c9.png)

I'm using Firefox.

Thanks!
Bye

**Comment by sanderfrenken** [comment]
Hmm I saw the bodies are not auto selected, can you select some items in order to see whether it is drawing then?

**Comment by manucontrovento** [comment]
I think I understood better. The problem seems to be that bodies are not auto selected as you say, and images loading is quite slow, so I thought it was not working:

![immagine](https://user-images.githubusercontent.com/56541575/139646954-29ee0ba1-d5d9-4f86-bf49-b93782524d25.png)

**Comment by sanderfrenken** [comment]
great, happy to hear it works! I might have a look at the loading time indeed, parsing the HTML takes a while atm.
