### ISSUE TITLE
Someone has stolen your product-He refers to it as the Chinese-made version

### ISSUE THREAD

**Issue by korman** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#150]
Look this: http://150.158.78.78:21422

I don't know if the author can access this website, he may have closed it, or maybe it is blocked except for Chinese websites, but I can provide some screenshots.

I can help you translate the Chinese on the second image:

"One year later, he's here! Pixel Character Generator, a Chinese-made open-source free tool."

LOL

![image](https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/assets/392256/f706799a-8955-4a77-8c62-233b694b8047)

![haha01](https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/assets/392256/068b5ee5-5810-4a75-a0f4-6cdd303b9752)

**Comment by jrconway3** [comment]
As long as this is properly licensed this is absolutely legal and there's nothing wrong with this. All Open Game Art assets are sourced in Creative Commons (or OGA-BY, which is a slightly looser version of creating commons licenses). This means as long as credit is given and links are made back to the original assets these assets can be reused and redistributed.

I can even see right here in the screenshot that OpenGameArt.org is referenced here, so I think this is perfectly legal. These assets also come from opengameart.org as well.


Its only a problem if they try releasing it in looser licenses than what licenses are currently provided for all existing assets.

**Comment by jrconway3** [comment]
Huh so the credits generation is a bit wonky. Still, it is pulling credits straight from OGA and listing licenses.


Its going to be rather hard to address issues in Chinese but they are at least _trying_ to get credits out in some way. Its possible someone may want to reach out to them to help them fix the attribution, but those credits would not come to here but to OGA instead. This application is also based on assets from OGA, but we have an intricate credits system to list credits of all assets and link the assets back to OGA. And OGA also links back here as well.

**Comment by jrconway3** [comment]
Sanderfrenken hasn't addressed this yet, but I did notice something else I wanted to comment on:
"Chinese-made open-source free tool"

So here's the thing. China often does this kind of thing, I get it. Its been happening in video games for a long time. However, this tool they created using open source assets is not the same tool as this Universal LPC Spritesheet Character Generator. Its a totally different tool that's simply using the same open source assets. As such, its entirely possible this specific tool is Chinese-made, and they're simply using legally available open source assets with proper credits.


...its also possible they're not using proper credits, I can't say that for sure. However, again, their generator is clearly a lot different from this generator. Its not the same design at all. If it was stolen code, it wasn't stolen from this repository most likely. Its also possible they made the generator from scratch (like how Guarav made this generator, and Sanderfrenken later completely rewrote it).

Its really hard to say without English being a first language.

**Comment by sanderfrenken** [comment]
I agree with @jrconway3 , as far as I can see there is nothing really wrong with the generator created.

This project of mine here has been based on Guarav's work, and if anyone wants to use this generator now to branch of sth new, that I can only encourage. I someone would like to copy it 1:1 that is also fine, there is no restriction I posed on the sources present in this repo.

wrt the artwork, its a different story. Proper credits should be given to the real authors. In this generator, that is nicely facilitated (IMO). In the Chinese one, I am not sure what I am looking at. But in the end it's up to the creator of a EG commercial game to provide proper crediting when certain assets are used. 

So to conclude, I don't think this alternative generator does anything wrong. At least not offending with the work done in this repo. Still, interesting to see!

**Comment by jrconway3** [comment]
My biggest concern is that they're not handling the licensing correctly, but its hard for me to tell what's going on there. The credits they're doing are a bit awkward. Still, though, that doesn't have anything to do with this repo. And they do have _some_ sort of credits in place at least, so at the very least they appear to be trying to credit the correct sources.
