### ISSUE TITLE
Issues with weapon preview images

### ISSUE THREAD

**Issue by ReneeIbeji** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#153]
There seems to be issues with the preview images for some weapons, this seems to be because those items are only have sprite sheets for some custom animations which don't comply with the standards of the main character sprite sheet.
I'll propose a solution I am working on as a pull request. 
![image](https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/assets/110279391/3450c1da-d611-4483-ac9b-6d5f5a25f276)

**Comment by jrconway3** [comment]
Yeah that makes sense. A lot of weapon animations use "oversize" animations.
