### ISSUE TITLE
Hats -> Tricorne thatch: All color options are the same colored sprite

### ISSUE THREAD

**Issue by jcoppage** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#16]
Hi sanderfrenken. Thank you so much for putting this together and having it available to us hobbyists/indie developers.  One issue: under the LPC Sprite Sheet Generator (https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/), the Tricorne thatch section under hats, the sprite does not change when selecting different color options. It just stays as the brown colored tricorne thatch sprite.  Thought I would point that out.  Thanks!

Jeff

**Comment by sanderfrenken** [comment]
Glad to hear you like the generator! And thanks for the reporting the issue, I asked the author of the assets if he can give the correct colored sheets, and will update them rightaway when I get them. Thanks again!
