### ISSUE TITLE
Missing glove

### ISSUE THREAD

**Issue by afflerbach** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#178]
The left hand glove is missing on both the top-left [male](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&gloves=Gloves_black&sex=male) and [muscular](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&gloves=Gloves_black&sex=muscular) sprites.

The _zombie_ and _skeleton_ sprites are affected as well.

**Comment by jrconway3** [comment]
Thanks for pointing this out. I'll probably get to it eventually. Tbh, I think I'd like to map the gloves to all frames rather than just fix that one missing asset, but that would take a while and I slowed down a bit recently on updating these assets. I will get back to it sooner or later, though.

**Comment by jrconway3** [comment]
I waited long enough for this. I'll include this in the next batch of updates, I just wanted to finish #141 first. It shouldn't be too hard to redraw the gloves over all frames.

**Comment by jrconway3** [comment]
Yeah this shouldn't be too bad. Looks like there's only one type of gloves. IIRC, Muscular has an extra pixel depth so theoretically, it might be desirable to give them a separate set of gloves.

For now I am not worried about that, though. I'm going to prioritize finishing just male and female across all frames.

I just need to rotate the existing frames here and there for the new positions to figure how how the other hand positions should look, and then I can fine-tune where needed.

**Comment by jrconway3** [comment]
This should be done soon. However, I don't like the dark border between the gloves and the rest of the arm. I'm not going to remove it, I'm keeping this consistent. However, maybe eventually I might draw a variant with that removed, and also longer gloves as well that go partway up the arm.
