### ISSUE TITLE
Open index.html in my local folder, the page show none of sprites

### ISSUE THREAD

**Issue by zephyrflow** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#187]
I download the code zip, and open the index.html under root, in browser I can not see any sprites.

**Comment by zephyrflow** [comment]
I found the reason. The root folder should be run as a local http server. Just open index.html file in browser may cause local file access rejection.

**Comment by Saber-Null** [comment]
thanks, i couldn't figure out what was going on lol
