### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by Bibisik** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#191]
Help me understand how to start a project and make my own character? I clone the repository, run index but it doesn't work in the browser

**Comment by Saber-Null** [comment]
I'm having the same issue, I may just be dumb tho lol

**Comment by jrconway3** [comment]
https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/

**Comment by jrconway3** [comment]
The webpage is linked under "About" on the main index page. You don't need to clone the repository locally to run it.

**Comment by Saber-Null** [comment]
I'm just going to assume its some weird issue with my pc and js then. my computer refuses to run the scripts, and after hours of tinkering and guides on how to fix the issue, js just wont work

**Comment by Saber-Null** [comment]
oki, so i actually found the issue with this for me. zephyrflow, brought this up in a previous post and you may have to change the browser setting to allow local execution. I did this and the sprites are now showing when i run locally

**Comment by jrconway3** [comment]
So for me I had to set up a localhost development environment server (XAMPP).

I thought you could just run HTML and JS in a browser window but I couldn't get it to work. I can attempt that method myself and see if it would without a local environment.
