### ISSUE TITLE
Issue found with the helmet wings sprites

### ISSUE THREAD

**Issue by Shroksy** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#193]
I was going through which sprites I want to use for my game and saw that the helmet wings hat accessory has the right/left animations flipped. For example, the animation for walking left has the sprites facing the right direction, whereas the animation for walking right is facing the left direction.

Here's an image with a visual representation of the issue:

![image](https://github.com/user-attachments/assets/7f000795-226e-47f6-b661-709d0cb91129)

EDIT: I'd also like to point out this is the only hat accessory with this specific issue

**Comment by jrconway3** [comment]
Thanks! I probably forgot to flip them on that side. My bad.

**Comment by jrconway3** [comment]
Looks like the bg and fg are flipped. When I expanded these to all frames, I may have accidentally made the bg the fg, and fg the bg. That's what messed up here. I went through these so quickly I probably screwed it up.
