### ISSUE TITLE
issue on all-credits csv downloaded from the generator

### ISSUE THREAD

**Issue by ralke1** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#195]
Hello, first of all, thanks for all the work!

I am currently using the LPC Spritesheet generator, huge fan btw, and i need/want to give the right credits, so i download the "all-credits.csv" and it not really parseable at first. Maybe i fixed, could use some check -> [all-credits.csv](https://github.com/user-attachments/files/17276098/all-credits.csv)

if someone did not find it, i download it on "https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/" you can download a csv with "all-credits.csv" name ,as in the print:

![image](https://github.com/user-attachments/assets/d88b7468-6000-40de-8aa2-bbbcd6be8342)

 sorry, i didn't find it (csv) in the repo to make a new branch and a proper PR.

Hope it helps. 

Thanks for all the beautiful LPC art.

**Comment by jrconway3** [comment]
What exactly is the issue that you "could not parse it"? Can you clarify?

If there was a parsing error with the CSV it wouldn't be able to be used properly to extract the credits for the individual assets.


The credits CSV is right here, btw:
https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/blob/master/CREDITS.csv

Its just in the root directory of the repository, the `CREDITS.csv` file.

**Comment by ralke1** [comment]
I could not lint it or some lines would be errors on pandas.

With your guidance i did my best to make a fork and PR.

https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/196/files

So it's easier to check what i did to fix.

If you do need some prints after i'll be happy to take it, probably will use pandas to parse it and checking licenses columns unique.

**Comment by jrconway3** [comment]
Okay, looks good to me.
