### ISSUE TITLE
"Male" Equivalent to LPC Revised Clothing Assets

### ISSUE THREAD

**Issue by jrconway3** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#199]
With #141 now completed, we're still missing assets for the "Male" sets. This shouldn't take nearly as long as it took to complete them to begin with, but its still a lot of stuff to complete. This consists of:

1. Sleeveless Shirts: Standard, V-Neck, Scoop, Buttoned, Polo
2. Shortsleeve Shirts: Standard, V-Neck, Scoop, Buttoned, Polo
3. Longsleeve Shirts: Standard, V-Neck, Scoop, Buttoned, Polo
4. Cardigan
5. Creating Pants Variants From the Overalls
6. Leggings/Hose
7. Socks, Shoes, Boots
8. Shorts and Short Shorts

Some frames are identical to the other frame sizes, including most of the "shoot" frames and Eliza's combat frames, so that reduces the work required to be done in these contexts.

**Comment by clementcontet** [comment]
Keep up your excellent work!
Once completed, my footballers (males and females) will finally have their new "sprint" animation 😁 (www.supercodingball.com)

**Comment by jrconway3** [comment]
Okay, thanks for the update. Yeah, I didn't do Male yet because Eliza didn't have that one, I only did Female and Teen instead. I don't get many suggestions, but when I do I try and prioritize what's being asked for more, otherwise I prioritize what I'd prefer to work on personally.

I'll look into finishing up these assets after I'm done with Body Armour.

**Comment by jrconway3** [comment]
I started working on this for a short while, then Aseprite crashed when I was trying to save it, and then somehow my entire hard drive crashed... I literally have no idea how it happened, it was so weird.

I'm still trying to recover the hard drive, but at least my sprite updates are safe (they're in a private repo on Bitbucket which is also on my laptop, I only lost a small tiny bit of progress I started making on the pants, which I can easily get back anyway).


So yeah. That was weird....


That being said, it wasn't very hard at all to start making these updates. I just compared the Overalls, which are ALREADY complete, to the standard female/teen pants, cut off the tops, and made a few small tweaks. So this is relatively easy to do again. I just want to make sure I do everything I can to recover my data before continuing this.

Also it has set me back a bit, because I had started collecting all the data I needed to drop the Hats release on OGA, but that stuff I have lost (for now) unless I can recover it. So before I can drop the release on OGA I have to manually recreate the entire list I had started from scratch which is such a pain.

**Comment by jrconway3** [comment]
I think as a bonus I'm going to try making a skirt, too. I'll just stick with a skintight skirt at first as its easier to do that. My plan would be a long one and a knee-length one. It'll just be running off on the existing assets so not hard to implement.

Almost recovered my data now so I'll be starting on this soon-ish.

**Comment by jrconway3** [comment]
Cuffed Pants are about halfway done now, maybe a bit more. And the regular Pants will get done pretty quickly as well. What's nice is that a good chunk of frames are identical between versions, so I don't have to adjust every single frame.

Leggings and Socks are going to be a bit harder as I actually have to do something more there to fill them out. So what I might do is finish the pants and drop a PR for just the pants, then move on to Leggings, Hose, Socks, etc. Once the Leggings are done, Hose and Socks are super easy.

**Comment by jrconway3** [comment]
Cuffed Pants are done. I'll finish regular Pants in the morning. After that, I'll look into seeing how hard it will be to jump straight into hose and leggings.

**Comment by jrconway3** [comment]
Leggings (and Hose) are form-fitting to the legs, that's the difference. So its not going to be a quickie, but its still not THAT bad. In some cases the pants are already form-fitting, though I feel like that's a mistake in the original version of the Overalls I did previously.

**Comment by jrconway3** [comment]
I want to drop the Pants, Leggings/Hose, and Socks all at once. I got delayed on the pants because I had to fix up a few frames; the pant legs were narrower than female which didn't make sense, it must have been an issue with how the Overalls were configured.

That said, there's still a few frames left of the regular pants. At some point, though, I'll also look into meshing these pants and shirts with the regular ULPC shirts and pants, too. I think I can get away with just a few minor touchups to make the styles mesh up. The main difference seems to be that the regular pants and shirts have darker borders along the sleeves and bottoms.

**Comment by jrconway3** [comment]
Sorry, slight change of plans. I'm going to focus on just pants on the first update, though socks and shoes probably won't be too long after.

However, I'm going to add in the regular ULPC pants as well. The regular pants and regular leggings are almost identical. The main difference is the regular leggings drop the second-darkest non-border color in favor of only using the darkest non-border color, and it chops off the top pixel and the bottom pixel. This should be very easy to finish up based on the existing LPC Revised assets. So I'll drop them in as well.

In theory I probably could have just replaced them completely with the new ones, but I don't like the idea of doing that. There are subtle differences between the two versions.

**Comment by jrconway3** [comment]
Rather than clog this repo's issue list up, I created an issue list on my own fork instead for my personal projects:
https://github.com/jrconway3/Universal-LPC-Spritesheet-Character-Generator/issues/10

**Comment by jrconway3** [comment]
Just a quick update:

While I would prefer now to follow the cards on my fork instead of here, I did finally add some leg assets and I'm working on the last few now. Shoes are done (but not live) and I plan to have boots done tonight. Then Shorts are all that's left for these assets specifically. I'd like to drop all four of these at once to get them done.


Shirts will take a much longer time to finish up. I think at this time I kinda just want to get through all pants and skirt assets before even starting on shirts...
