### ISSUE TITLE
How to use this with Godot? Especially the one with none uniform sizes for rows

### ISSUE THREAD

**Issue by iMuhammadMustafa** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#201]
I'm trying to use the sprite sheet with Godot, the body works but the Sword and weapons have extra bigger size sprites at the bottom that makes me unable to use it with the animation player or the animated sprite. 

Is there a way to make it work without manually modifying the things I need?

**Comment by jrconway3** [comment]
I don't know much about Godot so I can't really comment there.

There's a couple of ways to handle it.

Its probably not impossible to parse out the oversized weapons separately. Though I can see the backslash animations being annoying (only Arming Sword has that so far but eventually I'd like to add other weapons to these new combat animations).

Personally speaking, eventually when I get around to try doing it, my thought process would be to use the full sprite sheet WITHOUT the weapons layered over the assets. Instead, download the weapons separately and layer them over the character model in the game itself. That would also make it easier to swap weapon styles if that's something you want in your game.

It also depends on your needs, though. Some people might prefer to download the parts individually and layer the assets themselves in a sort of in-game character creator.

**Comment by iMuhammadMustafa** [comment]
Yeah that's how I have it now, each part is separate in its own sprite sheet and this is working great for all parts except oversized weapon. 

For example ( These are random numbers)
- Body SpriteSheet is split into boxes of 32x32, and this is perfect
- Longsword sprite sheet however is split into 32x32 and then 64x64.. which is hard to work with differently sized sprites within the same spritesheet.. it's not a uniform size of columns and rows

**Comment by jrconway3** [comment]
So, just to clarify, the body sheet isn't 32 x 32. Its 64 x 64. The oversized animations are either 128 by 128 or even larger. I don't know who made the "even larger" animations, but mixing and matching larger animations will get increasingly annoying to deal with. Most oversized animations are 128x128, double the size of the base models.


In any case, the larger animations (128x128) need to be adjusted positioning-wise to shift them enough pixels over to line up with the main body. That's literally how its working in this generator as well; the generator is simply taking the existing base frame (without the sword), making it larger, and adding the sword over top.

What you basically need to do in this circumstance, I would assume, is when the attack animation happens, that is the only time the 128x128 sword animation gets laid over the 64x64 character model. So you would need a special interaction just for the attacks.


When facing north, only grab the north animations, frame by frame, and layer them -16, -16 over the character model, matching each frame of the slash animation with each frame of body's slash animation.


Also, just to confirm: the 64x64 sword animation, the one that's the same size as the body sprite, it isn't for the sword slash. From what I have seen, that one only adds the sword to walk and down. You can include that if you want, but its optional; sometimes you don't want the sword to be out all the time. Link in LTTP only has his sword out while attacking, for example.
