### ISSUE TITLE
Bedhead hair shows the naked skull on "die" animation

### ISSUE THREAD

**Issue by clementcontet** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#24]
For example: https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Humanlike_black&shoes=Shoes_brown&hair=Bedhead_black&legs=Pants_red&eyes=Eyes_brown&armour=Leather_blue

![image](https://user-images.githubusercontent.com/7261426/155957127-1855ef50-7ba4-4487-a5e6-41c561143ca9.png)

**Comment by sanderfrenken** [comment]
fixed
