### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by bluecarrot16** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#25]
I've noticed the loading time has crept up; it takes 4--6 seconds to load the generator on my machine. This isn't terrible in the grand scheme of things, but wondering if there are things we could do about this, since I suspect it will only get worse as more assets are added. 

Most of the time is spent in the `generateListHTML` function. A few ideas to investigate:

- The `template-general.html` file is requested by `XmlHTTPRequest` for each entry. Obviously this hits the cache, but I don't remember if there is an overhead to XHR even for retrieving cached files. We could try loading this template once to a global constant rather than each time
- There are lots of network requests to load the JSON files. I suspect it would be more performant if they were combined together into a single file. Obviously this would be worse for development, but could maybe be addressed with a build step
- `replaceDivs` calls `$.replaceWith` on the `<div>` elements used to indicate assets in the tree. Could this be refactored to use `$.html()` instead, [which is generally faster?](https://stackoverflow.com/questions/42728231/jquery-and-speed-of-replacewith-vs-html)

**Comment by sanderfrenken** [comment]
Yeah I know, thought about it as well. I think the three ideas you suggest might help to some extent, but in the end the current solution is just not that scalable (generating the html on load).

Hence, I was actually thinking to generate the HTML locally before pushing as pre-push hook.
Then once generated the script will also create hash of the file, which can be used to assess the integrity later. 
This is needed as we dont want people to manually change the generated index.html and then push that.

This will also require that I add a job on the CI that will actually also create the index.html, hash it and compare that hash with the hash of the current PR. If the don't match, the pipeline fails and one cant proceed with his/ her PR.

What would you think about that?

**Comment by sanderfrenken** [comment]
@bluecarrot16 I pushed a new change. In this change, and now the index.html is pre-generated. 

There is JS script [here](https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/blob/master/scripts/generate_html.js) (you can just run it with node) that uses the [source index](https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/blob/master/source_index.html) and generates the index.html from there.

I didnt polish it yet nor did I update the readme, I first wanted to confirm first that the page is loading faster now. Personally I think it is, what do you say?

**Comment by sanderfrenken** [comment]
Fixed
