### ISSUE TITLE
Additional animations

### ISSUE THREAD

**Issue by EtagiBI** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#28]
Hello,

Aren't you planning to add additional animations to a spritesheet?
For instance, jumping animation, damage taking animation, etc.

**Comment by sanderfrenken** [comment]
We are in the process of adding a running animation. But in general, adding new animations is a huge task, as it will affect all sheets. Feel free to contribute! 

Closing this issue now, thanks for your input!
