### ISSUE TITLE
body sprite sheet and longsword sprite sheet frame numbers not matching up??

### ISSUE THREAD

**Issue by jcoppage** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#29]
HI there, love this generator, I really appreciate you making this available.  In my game, I want to load the sprite sheets using the same frame numbers for the weapons/armor/body.  Using the same walking animation frame numbers for the body sheet and the longsword sheet, the long sword frames do not match. (Example: Walk left for the Body would be Frame numbers 117 to 125 based off 64x64.  But those frame numbers do not work for the longsword, and more than likely the other weapons.  Also, looks like the shields are a little off too.  The Plate armor works good though!)  Any thought on how I could get around this?  Thanks!
<img width="1106" alt="Screen Shot 2022-07-11 at 3 59 38 PM" src="https://user-images.githubusercontent.com/70357667/178372843-b3112d4f-70b1-4dee-a07a-7a9d481ed166.png">

**Comment by sanderfrenken** [comment]
Indeed the longsword is an oversize weapon, and therefore its attack animation is based on 192*192 pixel frames. That also means that the oversize weapon sheets are different from the non-oversized items. You would need to workaround this in your engine/ app yourself!

BTW sorry for the late reply!

**Comment by iMuhammadMustafa** [comment]
@jcoppage Have you found a workaround that?
