### ISSUE TITLE
Eye Wound Broken

### ISSUE THREAD

**Issue by Gastronok** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#33]
Older versions showed the Eye Wound.

There appear to have been changes to how heads are set up.

Now Eye Wounds are not visible, regardless of selections tatus.

**Comment by sanderfrenken** [comment]
Fixed in https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/36

**Comment by sanderfrenken** [comment]
thanks for reporting!

**Comment by Gastronok** [comment]
Thanks for maintaining this.
