### ISSUE TITLE
Ponytail2 hair has a light skin color artefact

### ISSUE THREAD

**Issue by clementcontet** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#34]
See: https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_black&head=Human_male_black&sex=female&hair=Ponytail2_black&dress=Dress_blue&clothes=Longsleeve_navy&legs=Pants_red&eyes=Eyes_brown

<img width="99" alt="ponytail2" src="https://user-images.githubusercontent.com/7261426/195536080-5794aca2-2b88-43c9-a093-d17dfb2e26a0.png">

**Comment by sanderfrenken** [comment]
fixed
