### ISSUE TITLE
Sleeveless shirts URL parameter not loaded

### ISSUE THREAD

**Issue by clementcontet** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#35]
When I load https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&clothes=Sleeveless_navy, the sleeveless shirt is not selected.

**Comment by sanderfrenken** [comment]
Fixed in https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/36, thanks for reporting!
