### ISSUE TITLE
Make sure all shoes/feet can be used with all bases

### ISSUE THREAD

**Issue by bluecarrot16** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#39]
I think all foot/shoe/boot sprites have been adapted to both male and female bases, so the `male` version should be usable with `muscular` and the `female` version with `pregnant` and `teen`. Need to review the JSON files to allow this in all cases.

**Comment by sanderfrenken** [comment]
fixed by https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/100
