### ISSUE TITLE
No more staffs?

### ISSUE THREAD

**Issue by jcoppage** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#52]
Where can I find the staffs? I thought they used to be on there.  Thanks.

**Comment by sanderfrenken** [comment]
they are there, [here for example](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&sex=male&hair=Shorthawk_ginger&bauldron=Bauldron_charcoal&weapon=Thrust_oversize_(attack_only)_8)
