### ISSUE TITLE
No sprites appear on webpage, can't interact with any menus

### ISSUE THREAD

**Issue by wubbles69** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#53]
Title says it all, really. ZorinOS

Cloned the local repo. Seems to work just fine if I click the link on github page.

**Comment by rdo** [comment]
This is due to recent changes with CORS policy. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp
Shortly, now you need local http server to launch index.htlm. I used https://www.rebex.net/tiny-web-server/
