### ISSUE TITLE
I'm going to use it in the service 'zep.us' how to show csv or Licenses

### ISSUE THREAD

**Issue by jkf87** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#56]
i want to use your project to make spritesheet for some custom character in zep.us (like gather.town)
how to show your licenses.
Is it possible to replace it by hanging a download link that shows copyright on the map?

**Comment by sanderfrenken** [comment]
Please refer to the readme for complete crediting instructions. I am not sure what you mean with `hanging a download link that shows copyright on the map` but the credits should cover each asset that you use, and they should always be accessible from your game. Hope that helps!

**Comment by jkf87** [comment]
clearly can acess link about copyright in map
