### ISSUE TITLE
Need support for Godot plugin

### ISSUE THREAD

**Issue by DrJamgo** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#57]
@sanderfrenken
I would like to make usage of LPC sprites easier for Godot users. 
The Idea is to export the generated sheet, keeping the layers seperated, to allow runtime modification (enabling layers, adding items/gear/etc). 

The exported credits CSV has almost all needed information to do that (except zpos). 
Adding the zpos to the credits feels out of place and bad design.

Also CSV is not the best format for Godot either as it is interpreted as _language translation file_ by default.. JSON would be a better choice.

What do you think?

**Comment by DrJamgo** [comment]
I have created a branch now to add an export button in JSON format. Please add me as contributor, so I can push it and open a PR.. Thanks!

**Comment by sanderfrenken** [comment]
I am not sure I fully understand your idea. If you like to use the separate layers (which I understand the use case for) then why would you need the generator? You could just take the sheets from the `/spritesheets` folder and import them directly into your engine.

As for the credits, you would need something to create that for you indeed. One way would be to use the generator, is that what you are trying to achieve? For creating PR's, you should already be able to do so. At least, PR's were created previously by others, so unless sth changed, you should be able to create a PR.

**Comment by DrJamgo** [comment]
I did start off just using the sheets and make an own layer editor as plugin. It is just much less usable and clunky then your web version.

The idea is:
- generate char with the generator
- copy the fata and meta as json to clipboard
- go to godot
- import the data from clipboard
- download the png files from web
- initialize the Nodes/Resources accordingly for usage

That way only the necessary files are in the project, not all.
Also with the url in the meta, one can just open the generator with same layers again to do modifications.
