### ISSUE TITLE
wish to switch from a 64x64 spritesheet to a 48x64 one.

### ISSUE THREAD

**Issue by jkf87** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#58]
Please let me know how to do this, I'd like to fork it and modify it and utilize it on my GitHub, I'll always credit you.

**Comment by sanderfrenken** [comment]
The thing is that some  of the frames extend beyond the 48 frame size. So they are mostly made for 64 frame size. The oversize weapons are even larger (192*192). So resizing to 48 will be impossible, unless you resize all sheets.
