### ISSUE TITLE
Lacking License info on multiple part of sprite

### ISSUE THREAD

**Issue by TunirWilliams** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#6]
weapons/oversize/oversizeNone.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK
body/male/human/light.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK
body/wounds/eye_blood.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK
eyes/male/blue.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK
beards/male/beard/brown.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK
facial/glasses.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK
feet/shoes/male/brown.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK
legs/armour/male/11.png,!MISSING LICENSE INFORMATION! PLEASE CORRECT MANUALY AND REPORT BACK VIA A GITHUB ISSUE,,,,,,,,NOK

**Comment by sanderfrenken** [comment]
Fixed most missing files in commit c67aa8365dc0687acc8d3b561e35535b2b09147d

Still some are missing, to get an overview open the console when opening the generator from your browser.
Will work on those in between, but feel free to chip in where possible :)
