### ISSUE TITLE
License filter?

### ISSUE THREAD

**Issue by DrJamgo** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#61]
I was wondering if a filter by license can be helpful to only show assets for the intended use.
e.g. exluding GPL v3.0 licenses (I know not much will be left but still ;-) )

That way files without proper credits entry could also be hidden by default, one would have to enable "UNKNOWN LICENSE" or something

**Comment by sanderfrenken** [comment]
I get the idea, but I prefer to keep the generator as "clean" from such specific features as possible. As you might have seen, it is already. a bit of feature creep and the logic isn't that well separated atm. You already have an implementation?
