### ISSUE TITLE
Weapons issues

### ISSUE THREAD

**Issue by bluecarrot16** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#62]
The weapons section could use some love. I'm trying to add some new weapons and updating old ones, and I've collected a list of issues I encountered along the way. We can create separate issues for these if that would be preferable:

- The organization of [spritesheets/weapon/](https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/tree/master/spritesheets/weapon) is not very consistent, which makes it hard to figure out where to put things. Not sure the best approach here, but some thoughts:
    - It's confusing to need to sort weapons by animation ("thrust", "slash", "bow", etc.) when some weapons have multiple animations (halberd, simple staff); I am also drawing additional animations for sword, dagger, etc. so they will not fit neatly into one category. 
    - Most weapons use oversized frames, so they'll need a separate "universal" sheet
    - Since the v3 character bases use the same hand positions, there shouldn't be a need for separate male/female versions... probably...
    - I think we should try to separate weapons into distinct objects when there are recolors; e.g. it's confusing to me that [Thrust > Spear 2](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_spear_2), [Thrust > Spear black](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_spear_black), and [Thrust > simple staff](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_simple_staff) are all in the same category. 
    - I guess what I would propose is to make categories: "swords," "polearms," "bows", "bludgeons," "throwing weapons" etc., then have each distinct weapon type as an entry under one of those categories. Recolors should be grouped into the same entry as variants. 
- [x] Bows do not have walk animations; walk animations were drawn by pvigier here: https://opengameart.org/content/lpc-walk-animations-for-bows
- [x] Several bow variants are numbered; these should probably be broken up by type ("great bow," "recurve bow", etc.), then different recolors named (or better yet, generated programmatically)
- [x] Shovels: there are 3 shovels: I think 1 and 2 should be removed in favor of 3. 
    1. (1) [Weapons > Thrust > Shovel 2](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_shovel_2) 
    2. (2) [Weapons > Thrust > Spade](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_spade)
    3. (3) [Tools > Thrust > Shovel](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_shovel)
- [x] Spears: [Thrust > Spear 2](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_spear_2) fixes the broken walk animations of [Thrust > spear](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_spear); I propose replacing Thrust > spear with Thrust > spear 2
    - [x] There are several spear recolors; these should be grouped into a separate weapon type
- [x] Axes: there are three axes. I propose deleting 2--3 in favor of 1. 
    1. (1) [Tools > Smash > Axe](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Smash_axe)
    2. (2) [Weapons > Slash > Axe](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Slash_axe)
    3. (3) [Weapons > Slash > Axe 2](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Slash_axe_2)
- [x] Tools > Smash > {Axe, pickaxe, (war)hammer} don't have walk animations: [example](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Smash_axe). pvigier [drew nice ones here](https://opengameart.org/content/lpc-smash-weapons) that could be added. 
- [x] Weapons > Slash oversize > {[Flail](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Slash_oversize_flail), [Waraxe](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Slash_oversize_waraxe)} should be split into layers and merged into Weapons > Slash oversize layered. Layered versions will work better with different heads and body types than masked versions. I obtained source images from BenCreating and am working on this. 
- [x] [Weapons > Thrust oversize (attack only)](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Thrust_oversize_(attack_only)_27) is a weird hodge-podge of lots of different stuff; there are lots of variants which are totally different types of weapons---some staffs, some spears, some tridents, etc.; they're all numbered instead of named too. None of them have walk animations, which would be neat to add at some point. 
- [x] Add pvigier's swords: https://opengameart.org/content/lpc-dcss-swords

**Comment by sanderfrenken** [comment]
fixed or converted to individual issues
