### ISSUE TITLE
Replace cutout weapons with layered versions

### ISSUE THREAD

**Issue by sanderfrenken** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#68]
This will allow to ditch the gender specific assets

**Comment by caseygrun** [comment]
Updated this submission which adds layered versions for most assets: https://opengameart.org/content/lpc-extended-weapon-animations

**Comment by bluecarrot16** [comment]
Updated this submission to add layered version of most weapons: https://opengameart.org/content/lpc-extended-weapon-animations

**Comment by sanderfrenken** [comment]
fixed in https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/76
