### ISSUE TITLE
Missing walk animations for tools section axe (fixed), hammer and pickaxe (fixed)

### ISSUE THREAD

**Issue by sanderfrenken** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#69]
Add walk animations from https://opengameart.org/content/lpc-hand-tools when they are finished.

**Comment by bluecarrot16** [comment]
For the most part it should be possible to adapt these from here https://opengameart.org/content/lpc-smash-weapons by splitting into layers as appropriate

**Comment by sanderfrenken** [comment]
Indeed, did it in https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/115 for the axe and pickaxe, only the hammer remains.

**Comment by jrconway3** [comment]
This hasn't been looked at in a while. Perhaps I can try and figure out how to get these done in preparation to work on more tools/weapons in the future.

**Comment by jrconway3** [comment]
So the main thing left is warhammer? Looks to me like its already done on pvigier's set, just need to drop it in.

**Comment by jrconway3** [comment]
I think it might benefit having more colors, but for now I just grabbed the hammer, put it into the ULPC, exported it, and I'll have it up in the next PR. Just to close this card out.

I double-checked to confirm, the male/female positions are slightly off, so I do have both versions present here.

**Comment by jrconway3** [comment]
Apparently "Teen" did not have support enabled for Tools, so I added that as well. I didn't add myself to the credits for Hammer because the asset was already done, I just dropped it into the universal sheet without much effort.
