### ISSUE TITLE
Z order of facial items too low

### ISSUE THREAD

**Issue by ChuckNeal** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#79]
The facial items (glasses, eyepatch, etc) are not rendering over heads. The z depth on all is set to 25 while the heads are set to 100 so they won't ever render. Probably should be around 125 in the JSON files. 

This really is a great tool. Thanks for all the hard work.

**Comment by sanderfrenken** [comment]
Fixed by https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/78
