### ISSUE TITLE
Capes are not working properly

### ISSUE THREAD

**Issue by sanderfrenken** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#85]
Behind is not drawn behind the body:

https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=none&head=Jack_O_Lantern_jack&sex=female&cape=Solid_pink

moreover, all behind assets are black colored:

https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/cape/solid_behind/blue.png

**Comment by ClayShoaf** [comment]
Looks like your body type somehow got changed to "none" If you change the color or special body type, it should add the body back.
