### ISSUE TITLE
Question: how did you overlay the weapons sprites with the character's?

### ISSUE THREAD

**Issue by lazarovziv** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#86]
Hi,
first of all, fantastic work, it's really cool what you're doing!
second, I'm trying to overlay the weapons images on top of the character's (after I created the entire body with the head) and the images don't match, the bodies' are 64x64 and the weapons are 128x128, and in the generator it's seems you aligned it perfectly. Can you share how you did that? Thank you very much, your time answering this question is much appreciated!

**Comment by lazarovziv** [comment]
the issue I encountered is with the slash/slash_reverse/thrust images

**Comment by sanderfrenken** [comment]
sorry for the late reply. Thanks for the compliments!
Weapons in some cases have a different frame size indeed. So what you need to do in your example:

Take every separate body animation frame (universal frame, 64*64) and center it in 128*128 frames. Then, draw over that the weapon sheet.

For JS reference code, you should checkout this method:
https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/blob/master/sources/chargen.js#L427

Hope that helps!
