### ISSUE TITLE
Shields/weapons switch sides from left hand to right hand

### ISSUE THREAD

**Issue by afflerbach** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#87]
Shields switch sides from left hand to right depending on which direction the character is facing: [example](https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&shield=Shield_crusader) 

The same applies to weapons.

**Comment by sanderfrenken** [comment]
that is correct indeed, the sprites are all so-called ambidextrous. This simplifies adding content a lot and won't be noticed too much by players usually.

https://allthetropes.org/wiki/Ambidextrous_Sprite
