### ISSUE TITLE
Link to online version seems broken

### ISSUE THREAD

**Issue by SanjoSolutions** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#92]
The link http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator seems broken. It now shows another page.

**Comment by sanderfrenken** [comment]
Where do you get this link from?

**Comment by SanjoSolutions** [comment]
On https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator the repository homepage URL.

**Comment by sanderfrenken** [comment]
ahh got it! Thanks, updated now
