### ISSUE TITLE
Slit skirt doesn't render with Male body type

### ISSUE THREAD

**Issue by The-Fireplace** [sanderfrenken/Universal-LPC-Spritesheet-Character-Generator#93]
https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_olive&head=Human_male_olive&sex=male&hat=Cloth_hood_brown&clothes=Longsleeve_brown&jacket=none&cape=none&sash=Narrow_sash_charcoal&legs=Slit_skirt_brown&shoes=none&gloves=none
Expected behavior: Slit Skirt is added to the sprite, since it is a selected option (or the option isn't given to choose a slit skirt with this body type)
Actual behavior: My character has no pants 🥲

**Comment by sanderfrenken** [comment]
Fixed in https://github.com/sanderfrenken/Universal-LPC-Spritesheet-Character-Generator/pull/96 using the female asset. This works well enough, as the skirt is slit anyway and it actually looks quite well on a male body as well :)
